### ISSUE TITLE
App rejected because plugins capabilities on iOS 10

### ISSUE THREAD

**Issue by rafaellop** [Heyzap/heyzap-cordova-extras#10]
I've seen in the Heyzap changelog for version 9.6.8 (https://developers.heyzap.com/docs/changelog) that the requirement of permissions description on iOS 10 like the `NSPhotoLibraryUsageDescription` or `NSBluetoothPeripheralUsageDescription` were removed. But today I switched to xcode 8 and built my app with the iOS the 10th SDK and my build has been rejected with the following:

```Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data.```

Same about `NSBluetoothPeripheralUsageDescription` and `NSCalendarsUsageDescription `. I did a little research and the capabilities are required for sure by the extra packages. Definitely Admob and Applovin but maybe other too. Would be nice to have them removed. They are completely unnecessary for the ads to be shown and only intimidate users.

I really hope the cordova version will be fixed soon. It's truly so buggy and nothing cannot be done here because the SDK is a binary. Please update the issues or there will be no other way than to switch to a different solution for cordova ads.

**Comment by ekilah** [comment]
The third party ads SDKs have required those plist items in the past, and some still do.
