### ISSUE TITLE
Installing from subdirectories with Cordova 7

### ISSUE THREAD

**Issue by beevelop** [Heyzap/heyzap-cordova-extras#12]
As of Cordova `v7.0.1` fetching subdirectories is not possible by default.
```sh
cordova plugin add https://github.com/Heyzap/heyzap-cordova-extras.git#:heyzap-cordova-vungle
support for subdirectories is deprecated and will be removed in Cordova@7
Error: --fetch does not support subdirectories
```

You have to explicitly provide the `--nofetch` argument to get it working again (for now):
```sh
cordova plugin add https://github.com/Heyzap/heyzap-cordova-extras.git#:heyzap-cordova-vungle --nofetch
```

Correlates with #4

**Comment by matrixreal** [comment]
same here

**Comment by ekilah** [comment]
@beevelop @matrixreal I had another user report this, and made several repos to help solve this. I was going to have them confirm one worked before doing the work on the rest of them. Can one of you try https://github.com/Heyzap/heyzap-cordova-adcolony and see if that solves your problem?

**Comment by beevelop** [comment]
@ekilah Works like a charm 👍

**Comment by ekilah** [comment]
Great, I will work on publishing the others to separate ones soon... thanks for confirming.

**Comment by lizistorm** [comment]
@ekilah I tried install with `cordova plugin add https://github.com/Heyzap/heyzap-cordova-adcolony.git` and it works perfect.

**Comment by beevelop** [comment]
@ekilah Awesome, thank you!

**Comment by ekilah** [comment]
The updates are now linked on https://github.com/Heyzap/heyzap-cordova/blob/df4cdd4868c9e51d492533e2ca239b0b58b97a8a/README.md#adding-third-party-sdks . This repo will be deprecated in favor of the separated ones listed there. 

thanks for reporting this!

**Comment by ekilah** [comment]
if there are issues in any of the third party updates, we'll track them on their own repos. Thanks.
