### ISSUE TITLE
Native Ads

### ISSUE THREAD

**Issue by quig** [Heyzap/heyzap-cordova-extras#13]
Hello,

Are native Ads supported by HeyZap ? When using the debug plugin, I can display them by clicking on the 'Native' button (AppLovin for example) but I do not find anything related in the documentation.

Thanks,

**Comment by ekilah** [comment]
Unfortunately this plugin does not support them at this time. This is a wrapper around the native SDK, so it's theoretically possible, however native ads are complex and we won't be adding it. It'd be possible for you or someone else to build, with sufficient knowledge of the Cordova environment.
