### ISSUE TITLE
Facebook SDK is OBSOLETE! Fix it asap!

### ISSUE THREAD

**Issue by rafaellop** [Heyzap/heyzap-cordova-extras#14]
Facebook reminds!

**Comment by rafaellop** [comment]
![fb](https://user-images.githubusercontent.com/8421184/30866516-c5cfcecc-a2d9-11e7-8e54-215efae2039a.png)

**Comment by ezpuzz** [comment]
has been updated, please try new version.

**Comment by rafaellop** [comment]
The new version displays nothing at all but errors!

> [Heyzap 9.14.1] HZHeyzapExchangeBannerAdapter - requestFailedWithError: Error Domain=com.heyzap.ads.exchange.banners Code=1 "(null)" UserInfo={error=no_fill}

> [Heyzap 9.14.1] Error loading Facebook banner: Error Domain=com.facebook.ads.sdk Code=1001 "No fill" UserInfo={NSLocalizedDescription=No fill, FBAdErrorDetailKey={
>     msg = "No fill";
> }}
> 

> [Heyzap 9.14.1] Error showing ad = Error Domain=HeyzapMediation Code=1 "An ad cannot be shown at this time. Either no available networks had an ad or segmentation settings prevented the show. Ad networks we checked: [Facebook Audience Network]" UserInfo={NSLocalizedDescription=An ad cannot be shown at this time. Either no available networks had an ad or segmentation settings prevented the show. Ad networks we checked: [Facebook Audience Network]}

And it's not about the fill. It does display the same error from all locations I've tried. Always errors and no fill. I use the newest heyzap-cordova available in the repository.
