### ISSUE TITLE
Obsolete Admob

### ISSUE THREAD

**Issue by rafaellop** [Heyzap/heyzap-cordova-extras#18]
On iOS xcode console:

> Google:HTML> You are currently using version 7.18.0 of the SDK. Please consider updating your SDK to the most recent SDK version to get the latest features and bug fixes. The latest SDK can be downloaded from https://goo.gl/UoiJ8F. A full list of release notes is available at https://developers.google.com/admob/ios/rel-notes.

**Comment by ekilah** [comment]
updated here: https://github.com/Heyzap/heyzap-cordova-admob
