### ISSUE TITLE
Apploving plugin doesn't install

### ISSUE THREAD

**Issue by rafaellop** [Heyzap/heyzap-cordova-extras#20]
It cannot be installed from subfolders since Cordova 7, but --nofetch param allows to do it. Nevertheless the plugin does not install. Here's how:

> cordova plugin add https://github.com/Heyzap/heyzap-cordova-extras.git#:heyzap-cordova-applovin --nofetch
> support for subdirectories is deprecated and will be removed in Cordova@7
> Fetching plugin "https://github.com/Heyzap/heyzap-cordova-extras.git" via git clone
> Error: Failed to fetch plugin https://github.com/Heyzap/heyzap-cordova-extras.git via git.
> Either there is a connection problems, or plugin spec is incorrect:
> 	Error: git: Command failed with exit code 128 Error output:
> Cloning into '/var/folders/4v/v4wb3sgd337cg3xn3bxpz2w80000gn/T/git/1509607112598'...
> error: RPC failed; curl 56 SSLRead() return error -9806
> fatal: The remote end hung up unexpectedly
> fatal: early EOF
> fatal: index-pack failed

**Comment by ekilah** [comment]
https://github.com/Heyzap/heyzap-cordova/blob/df4cdd4868c9e51d492533e2ca239b0b58b97a8a/README.md#adding-third-party-sdks lists the new locations to fix this. see #12
