### ISSUE TITLE
App stuck right after the launch

### ISSUE THREAD

**Issue by tolik85** [Heyzap/heyzap-cordova-extras#3]
Hi,

After installing the Admob plugin on my ionic app, the app is stuck right after the launch.
It's not getting stuck if I install other networks, such as Heyzap, Vungle of Facebook Audience.

Can you please advise?

iPhone 6S, iOS 9.2

Thanks,
Nathan

**Comment by KarimP** [comment]
Hi Nathan,

Sorry for the late reply. I'm able to successfully add the admob plugin to a blank ionic app.

Is there any specific error that you encounter when the app gets stuck (anything in the web inspector or Xcode console)? Also, how are you adding the heyzap-cordova and heyzap-cordova-admob plugins and where are you calling `HeyzapAds.start` in your ionic app?

Regards,
Karim

**Comment by hassankhan** [comment]
Hi @KarimP, I'm having the same troubles. Xcode doesn't show any errors, it just hangs on launch. If I remove the third-party SDKs and only keep `heyzap-cordova`, it then works.

**Comment by hassankhan** [comment]
My app worked after removing the Admob plugin, but your mileage may vary
