### ISSUE TITLE
Separate into repos

### ISSUE THREAD

**Issue by hassankhan** [Heyzap/heyzap-cordova-extras#4]
Hi there, would it be possible to split this repo into smaller repos? I only ask because it takes a significantly longer time for Ionic/Plugman to grab the repo if it's a branch.

**Comment by KarimP** [comment]
@ekilah thoughts?

**Comment by ekilah** [comment]
I don't have an opinion, other than separate repos might make maintaining the project a bit more of a hassle.

**Comment by ekilah** [comment]
Done, see #12.
